Attribute VB_Name = "ModulMain"
Public Lokasi_File_Konfigurasi As String
Public Lokasi_File_Bahasa As String
Public Lokasi_File_Server As String

Public IDUser As String
Public NamaUser As String
Public Gender As String
Public LastLogin As String
Public UserPin As String

Private Const BackDoor = "64F3D3E307E7274575F48533" 'The Command Line Switch is /SIPLite2017

Private Const CopyrightMain1 = "F48464741474341424F27BD208371727A708674774"
Private Const CopyrightMain2 = "2565B70787C7D637876674"
Private Const CopyrightMain3 = "74C7C7C87897687738032828573747C7924737745223"

Public VersiPro As Boolean
Public Registered As Boolean
Public RegisterAs As String
Public SudahMasuk As Boolean

Public strUserAktif         As String
Public strNamaUserAktif     As String
Public strJabatan           As String
Public strRegistered        As String
Public strKodeUser          As String

Sub Main()
On Error GoTo Error_Code

Lokasi_File_Konfigurasi = App.Path & "\Config\Config.ini"
'Lokasi_File_Bahasa = App.Path & "\Languages\"
Lokasi_File_Server = App.Path & "\Config\Server.dat"

    VersiPro = False
    Registered = False
    RegisterAs = "Charles Neo"

If Dir(App.Path & "\Config\Config.ini") <> "" Then
    Call CopyrightMain
    Call OpenMain
Else
    MsgBox "File Konfigurasi Tidak Ditemukan Akan Membuat Ulang File", vbCritical + vbOKOnly, "File Konfigurasi"
    Call MakeINI
End If

Exit Sub
Error_Code:
    MsgBox err.Description & vbCrLf & vbCrLf & strSQL
End Sub

Sub OpenMain()
On Error GoTo Error_Code

    If UCase(Command$) = UCase(Decrypt(BackDoor)) Then
        VersiPro = True
        Registered = True
        RegisterAs = "DEVELOPER SIPLite"
        
        FormMain.LabelForgot.Visible = True
        FormMain.LabelCreate.Visible = True
        FormMain.TombolProfile.Visible = True
        FormMain.Show
    ElseIf UCase(Command$) = UCase("/About") Then
        'MsgBox "Create by Charles Neo", vbInformation + vbOKOnly, "RiauKode"
        End
    Else
        FormMain.Show
    End If
    
Exit Sub
Error_Code:
    MsgBox err.Description & vbCrLf & vbCrLf & strSQL
End Sub

Sub CopyrightMain()
FormMain.LabelCopy.Caption = Decrypt(CopyrightMain1)
FormMain.LabelCopyURL.Caption = Decrypt(CopyrightMain2)
FormMain.LabelCopyLegal.Caption = Decrypt(CopyrightMain3)
End Sub

Sub MakeINI()
Dim Fnum As Integer, i As Integer
Dim ArchivoINI As String
Dim intClave As Integer
Const ATTR_DIRECTORY = 16
On Error GoTo Bitch

If Dir$(App.Path & "\Config", ATTR_DIRECTORY) <> "" Then
    RmDir (App.Path & "\Config")
    MkDir (App.Path & "\Config")
Else
    MkDir (App.Path & "\Config")
End If

ArchivoINI = App.Path & "\Config\Config.ini"

If Dir(ArchivoINI) <> "" Then
 SetAttr ArchivoINI, vbNormal
 Kill ArchivoINI
End If
    Fnum = FreeFile
    Open ArchivoINI For Output As Fnum
    Print #Fnum, "###################################################################"
    Print #Fnum, "### DO NOT EDIT THIS FILE CONFIGURATION MANUAL DO THIS FROM APP ###"
    Print #Fnum, "###################################################################"
    Print #Fnum, ""
    Print #Fnum, "[Settings]"
    
    Print #Fnum, "Language=Indonesia"
    Print #Fnum, "FullScreen=True"
    Print #Fnum, "Sidebar=0"
    Print #Fnum, "Form_Top=525"
    Print #Fnum, "Form_Left=615"
    Print #Fnum, "Form_Height=9810"
    Print #Fnum, "Form_Width=19215"
    Print #Fnum, "Color=2"
    Print #Fnum, "Beranda=1"
    Print #Fnum, "Background="
    Print #Fnum, "Badge=True"
    Print #Fnum, "Remember=0"
    
    Print #Fnum, ""
    Print #Fnum, "[String]"
    Print #Fnum, "StringCode="
    
    Print #Fnum, ""
    Print #Fnum, "###################################################################"
    Print #Fnum, "### DO NOT EDIT THIS FILE CONFIGURATION MANUAL DO THIS FROM APP ###"
    Print #Fnum, "###################################################################"
    Close Fnum
    
Exit Sub
Bitch:
    MsgBox err.Description & vbCrLf & vbCrLf & strSQL
End Sub
